site_name: 我的设计文档

theme:
  name: "material"
  language: "zh"
  palette:
    favicon: docs/img/favicon.png
    # # Palette toggle for light mode
    # - scheme: default
    #   primary: "deep purple"
    #   toggle:
    #     icon: material/brightness-7 
    #     name: Switch to dark mode

    # # Palette toggle for dark mode
    # - scheme: slate
    #   primary: "deep purple"
    #   toggle:
    #     icon: material/brightness-4
    #     name: Switch to light mode
  

plugins:
- mkdocstrings:
    handlers:
      python:
        paths: [src]
- search
- blog

nav:
- 开始: 开始.md
- 函数: 函数.md