name: ci 
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: check code
        uses: actions/checkout@v4
        with:
          server-url: https://1648857133.github.io/mydocs/

      - name: set up py
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: install dependencies
        run: |
          pip install mkdocs
          pip install mkdocs-material
          pip install mkdocs-blogging-plugin  # 记得安装其他依赖的库
          pip install "mkdocstrings[python]"
        
      - name: build mkdocs site
        run: mkdocs build
        working-directory: ${{ github.workspace }}


      - name: deploy
        run: mkdocs gh-deploy --force
      
      